### PR TITLE
Clippy fixes

### PR DESCRIPTION
**Pull request by jhaye**
This resolves almost every Clippy warning and error. The thing I'm a bit worried about is that runtime behaviour was reliant on the disagreeing trait definitions for `PartialOrd`, `PartialEq`, and `Hash` which was fixed in 875f2b508d9ecf4f6aec335be21f3ad0635a8ec9. These were outright errors reported by Clippy. Here is an [example](https://rust-lang.github.io/rust-clippy/master/index.html#derive_hash_xor_eq) for such a lint.

I'll run all benchmarks next week with these changes and see if anything breaks.

### CODE REVIEW

**Comment by jhaye** [comment]
This doesn't appear to be breaking anything, so I'm merging.

image

**Comment by lhstrh** [comment]
Thanks, @jhaye!

**Comment by cmnrd** [comment]
Thanks! Interesting that this cleanup also improved performance! Does this fix all the warnings reported by Clippy? I am wondering whether we should introduce a CI pass that runs Clippy and fails if there are any warnings. We could also make this part of the existing build CI job.

**Comment by jhaye** [comment]
Some of Clippy's lints help performance, yes. For example Clippy might detect unnecessary cloning and suggest removing it. However I did not fix all warnings. IIRC there were two lints regarding cognitive complexity of the code which I didn't touch, because they would require structural changes where I would have to invest a lot of time into understanding the structure in the first place and thus I did not deem those fixes to be worth it.

You can however selectively disable specific lints, either from the CLI or from the code itself. So we definitely could integrate Clippy into the CLI pipeline.

**Pull request merged**
